<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/20
 * Time: 10:57
 */
namespace app\api\controller;
use app\api\controller\Weixin;
use app\api\model\Users;
use app\api\service\Token;
class Login extends Base{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function index($code = ''){
        $weixin = new Weixin();
        $openid = $weixin->GetOpenid($code);
        $post = I('post.');
        if($openid){
            $userinfo = Users::get(['openid'=>$openid]);
            $token = $userinfo['token'];
            $token_expres = Token::checkTokenExpress($token);
            if($userinfo){
                if($token_expres === true){
                    $token_express = $userinfo['token_express'];
                }else{
                    $express = Token::updateTokenExpress($token);
                    $token = $express['token'];
                    $token_express = $express['express'];
                }

                returnOk(['msg'=>'请求数据成功','token'=>$token,'token_express'=>$token_express,'user_id'=>$userinfo['user_id'],'openid'=>$openid]);
            }else{
                $user_id = Users::addUser($openid,$post);
                $info = Users::get($user_id);
                returnOk(['msg'=>'请求数据成功','token'=>$info['token'],'token_express'=>$info['token_express'],'user_id'=>$user_id,'openid'=>$openid]);
            }

        }else{
            returnBad(['请求openid失败']);
        }
    }


}
